### PR TITLE
Solve #26 and #27

### PR DESCRIPTION
**Pull request by thenewvu**
Please review this.

### CODE REVIEW

**Comment by thenewvu** [comment]
ping @cjihrig @arb

**Comment by cjihrig** [comment]
I'm traveling, and will take a look once I'm home. Sorry for the delay.

**Comment by cjihrig** [comment]
Thanks for the PR. Replaced by 6b6044eca61b88f62b531ea0d41d19049741ed06.

**Comment by thenewvu** [comment]
Thank you :)

**Pull request closed without merging**
